sudo: required
services:
  - docker

before_install:
  - docker build -t andropovbr/frontend -f Dockerfile.dev .

script:
  - docker run andropovbr/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "react-frontend"
  env: "ReactFrontend-env"
  bucket_name: "elasticbeanstalk-sa-east-1-643636865452"
  bucket_path: "react-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_id:
    secure: $AWS_SECRET_KEY